apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudshop-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: nginx:alpine # Simple frontend pour l'exemple
        ports:
        - containerPort: 80