apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: cloudshop-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Sur Azure AKS, "default" ou "managed-csi" est souvent la StorageClass par défaut
  storageClassName: default