# Clé unique du projet (doit correspondre à celle créée dans l'interface SonarQube)
sonar.projectKey=streambox-backend

# Le nom qui s'affichera dans le dashboard
sonar.projectName=StreamBox Backend

# Version du code (peut être dynamique, ici hardcodé pour l'exemple)
sonar.projectVersion=1.0

# Où se trouve le code source à scanner ?
sonar.sources=app/backend

# Encodage
sonar.sourceEncoding=UTF-8