apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # C'est magique : ça demande une IP publique à Azure
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Le port exposé sur internet
      targetPort: 5000 # Le port de ton application Flask