name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ON SUPPRIME L'ÉTAPE "Azure Login" QUI BLOQUAIT.

      # Nouvelle méthode : Connexion directe avec Docker
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build et Push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app/backend
          push: true
          # On utilise le secret username pour construire le nom de l'image dynamiquement
          tags: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/backend:v1